# Generated by Django 2.0.12 on 2020-05-18 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200514_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField(unique=True)),
                ('symbol', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
    ]
