# Generated by Django 2.0.12 on 2020-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='symbol',
            field=models.TextField(),
        ),
    ]
