# Generated by Django 2.0.12 on 2020-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200518_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='name',
            field=models.TextField(),
        ),
    ]
