# Generated by Django 2.0.12 on 2020-05-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200518_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='currency',
            field=models.OneToOneField(default='1c2dbe51-0e0f-431f-b914-2b49f3b465a8', on_delete=django.db.models.deletion.CASCADE, related_name='user_account_currency', to='accounts.Currencies'),
            preserve_default=False,
        ),
    ]
