version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.config.wsgi:application --bind 0.0.0.0:8000 --settings=core.config.prod
    volumes:
      - static_volume:/code/core/staticfiles
      - media_volume:/code/core/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/core/staticfiles
      - media_volume:/core/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:

